name: cua_finanzas
channels:
  - defaults
  - conda-forge/osx-arm64
dependencies:
  - python=3.10.13
  - pandas=2.0.0
  - requests=2.31.0
  - sqlalchemy=2.0.21
  - psycopg2
  - pyarrow=11.0.0
  - numpy=1.25.0
  - wordcloud=1.9.1
